<?php
/**
 * @var $this CustomFormDecorator
 */

use Packaged\Tests\Form\Supporting\CustomDecoratorForm;
use Packaged\Tests\Form\Supporting\CustomFormDecorator;

/** @var CustomDecoratorForm $form */
$form = $this->getForm();
?>
<div class="hidden"><?= implode('', $this->_getHiddenDecorators()); ?></div>
<?= $form->name->render(); ?>
<?= $form->email->render(); ?>
<?= $this->getForm()->getSubmitDecorator(); ?>
