language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - bash -c 'composer install --no-interaction --prefer-source -o'

script:
 - phpunit -c phpunit.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
